# -*- coding: utf-8 -*-
"""Copy of Keras Workshop.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9_iDbjUsuMto0ypTDhMU4j_kjuZvAbN

# Building Neural Networks in Python: A Practical Introduction
Welcome to the hands-on portion of the workshop! In this notebook, we will build our first neural network using Keras.

**Our Scenario:**
We have data on 1,000 students. We know their `hours_studied`, `previous_test_score`, and `attendance_rate`.
1. **Task 1 (Classification):** Can we predict if a student will **Pass or Fail**?
2. **Task 2 (Regression):** Can we predict their **Exact Final Score**?
"""

import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Input
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import confusion_matrix
import matplotlib.pyplot as plt
from sklearn.metrics import confusion_matrix, ConfusionMatrixDisplay

# Set random seeds for reproducibility
np.random.seed(42)
tf.random.set_seed(42)

print("Libraries loaded successfully! TensorFlow Version:", tf.__version__)

# --- 1. GENERATE SYNTHETIC EDUCATIONAL DATA (NON-LINEAR) ---
n_samples = 2000

# Features
hours_studied = np.random.normal(50, 15, n_samples)
previous_score = np.random.normal(70, 10, n_samples)
attendance_rate = np.random.uniform(0.6, 1.0, n_samples)

# Continuous Target
# 1. Interaction: Studying is exponentially more effective if attendance is high
# 2. Quadratic Penalty: Diminishing returns on extreme studying
base_knowledge = (previous_score * 0.4)
effort = (hours_studied * (attendance_rate ** 2) * 0.8)
burnout_penalty = ((hours_studied - 50) ** 2) * 0.02

final_score = base_knowledge + effort - burnout_penalty + np.random.normal(0, 5, n_samples)
final_score = np.clip(final_score, 0, 100) # Keep scores between 0 and 100

# Binary Target
passed_class = (final_score >= 70).astype(int)

# Combine into a Pandas DataFrame
data = pd.DataFrame({
    'Hours_Studied': hours_studied,
    'Previous_Score': previous_score,
    'Attendance_Rate': attendance_rate,
    'Final_Score': final_score,
    'Passed': passed_class
})

print("Dataset generated!")
data.head()

"""### Step 1: Prepare the Data
Neural networks need scaled numbers. Note that `Previous_Score` is a value between 0 and 100, but `Attendance_Rate` is a decimal between 0 and 1. This scaling difference is problematic for neural networks.
"""

# 1. Isolate Features (X) and Targets (y)
X = data[['Hours_Studied', 'Previous_Score', 'Attendance_Rate']]
y_classification = data['Passed']
y_regression = data['Final_Score']

# 2. Train/Test Split (80% for training, 20% for testing)
  # NOTE: Python is very sensitive to the order that train_test_split() is specified
X_train, X_test, y_class_train, y_class_test, y_reg_train, y_reg_test = train_test_split(
    X, y_classification, y_regression, test_size=0.2, random_state=42
)

# 3. Scale the Data using Z-scores (default for StandardScaler) mean = 0, variance = 1

# IMPORTANT: We call fit_transform() on training data and transform() on test data.
# fit_transform() learns the mean and standard deviation FROM the training set,
# then applies the scaling. If we called fit_transform() on the test set too,
# the scaler would learn different statistics from test data and "leak" information
# about the test distribution into our pipeline making our evaluation results
# overly optimistic and unreliable in production.

scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

print(f"Training data shape: {X_train_scaled.shape}")
print(f"Number of features: {X_train_scaled.shape[1]}")

print(f"Testing data shape: {X_test.shape}")
print(f"Number of features: {X_test.shape[1]}")

"""### Task 1: Binary Classification
**bold text**
Let's build a network to predict if a student **Passed (1)** or **Failed (0)**.

* **`Sequential()`**: This tells Keras we are building a model layer-by-layer, in a straight line from input to output.
* **`Dense(...)`**: This creates a "fully connected" layer, meaning every neuron connects to every neuron in the previous layer.
* **`input_shape=(3,)`**: We must explicitly tell the model to expect exactly 3 features (Hours, Previous Score, Attendance).
* **`activation='relu'`**: The activation function applied to hidden layers to help the model learn complex, non-linear patterns.
* **`activation='sigmoid'`**: The activation function applied to our *final output layer*. It forces the network's final prediction to be a probability between 0.0 and 1.0.
"""

# Step 2: Define Architecture
class_model = Sequential()

# Input layer & First Hidden Layer
# We MUST tell it the input_shape (3 features)
class_model.add(Input(shape=(3,)))
class_model.add(Dense(16, activation='relu'))

# Second Hidden Layer
class_model.add(Dense(8, activation='relu'))

# Output Layer (1 node, sigmoid activation for binary probability)
class_model.add(Dense(1, activation='sigmoid'))

# Step 3: Compile the Model
class_model.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Step 4: Fit the Model
print("Starting training...")
class_history = class_model.fit(
    X_train_scaled,
    y_class_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2, # Hold out 20% of training data for validation
    verbose=1
)
print("Training Completed")

"""### **Task 2: The Regression Pivot**
What if we don't just want to know if they passed, but we want to predict their **exact Final Score**?

Notice how the core architecture stays the same. We only need to change two things:
1. The output activation becomes **`linear`** (or blank) so it can predict any number.
2. The loss function becomes **Mean Squared Error (`MSE`)**.
"""

# Step 2: Define Architecture
reg_model = Sequential()
reg_model.add(Input(shape=(3,)))
reg_model.add(Dense(16, activation='relu'))
reg_model.add(Dense(8, activation='relu'))

# CHANGED: linear activation. We want a continuous number.
reg_model.add(Dense(1, activation='linear'))

# Step 3: Compile the Model
# CHANGED: Using Mean Squared Error instead of crossentropy
reg_model.compile(
    optimizer='adam',
    loss='mse',
    metrics=['mae']
)

# Step 4: Fit the Model
print("Starting regression training...")
reg_history = reg_model.fit(
    X_train_scaled,
    y_reg_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=1
)
print("Training Completed")

"""### **Visualizing the Learning Process**
Numbers in a terminal are great, but plotting the loss tells the real story of how our networks learned over time.

We are looking for two things:
1. **The training loss should go down.** This means the optimizer is doing its job and finding better weights.
2. **The validation loss should follow it.** If the training loss keeps dropping but the validation loss starts rising, our model is **overfitting** (memorizing the training data instead of learning general rules).

### Note:
We used well behaved synthetic data so these will be **very** well behaved plots.
"""

import matplotlib.pyplot as plt

# Set up a figure with two side-by-side plots
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(14, 5))

# --- Plot 1: Classification Loss ---
ax1.plot(class_history.history['loss'], label='Training Loss', color='blue')
ax1.plot(class_history.history['val_loss'], label='Validation Loss', color='orange')
ax1.set_title('Classification: Cross-Entropy Loss')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True, linestyle='--', alpha=0.7)

# --- Plot 2: Regression Loss ---
ax2.plot(reg_history.history['loss'], label='Training Loss', color='blue')
ax2.plot(reg_history.history['val_loss'], label='Validation Loss', color='orange')
ax2.set_title('Regression: Mean Squared Error (MSE)')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Loss (MSE)')
ax2.legend()
ax2.grid(True, linestyle='--', alpha=0.7)

plt.tight_layout()
plt.show()

"""### **Final Evaluation**
Let's see how both correctly specified models perform on the 20% of data they have **never seen before**.
"""

# --- Baselines ---
# Before interpreting our results, we establish a "naive" baseline for each task.
# A baseline is the simplest possible model -- if our neural network can't beat
# this, it hasn't learned anything useful.

# Classification baseline: always predict the majority class
majority_class = y_class_train.mode()[0]
baseline_acc = (y_class_test == majority_class).mean()
print(f"Baseline Accuracy (always predict '{majority_class}'): {baseline_acc * 100:.2f}%")

# Regression baseline: always predict the training set mean
baseline_pred = y_reg_train.mean()
baseline_mae = (y_reg_test - baseline_pred).abs().mean()
print(f"Baseline MAE (always predict mean score of {baseline_pred:.1f}): {baseline_mae:.2f} points")

print("\n--- CLASSIFICATION RESULTS ---")
class_loss, class_acc = class_model.evaluate(X_test_scaled, y_class_test, verbose=0)
print(f"Model Accuracy:   {class_acc * 100:.2f}%  |  Baseline: {baseline_acc * 100:.2f}%  |  Improvement: +{(class_acc - baseline_acc) * 100:.2f}%")

print("\n--- REGRESSION RESULTS ---")
reg_loss, reg_mae = reg_model.evaluate(X_test_scaled, y_reg_test, verbose=0)
print(f"Model MAE:        {reg_mae:.2f} pts  |  Baseline: {baseline_mae:.2f} pts  |  Improvement: -{(baseline_mae - reg_mae):.2f} pts")

print("\n--- CONFUSION MATRIX ---")

# Predictions
y_pred = (class_model.predict(X_test_scaled) > 0.5).astype(int)

# Compute confusion matrix
cm = confusion_matrix(y_class_test, y_pred)

# Plot
fig, ax = plt.subplots()

ax.matshow(cm * 0, cmap="Greys")  # blank background

for (i, j), val in np.ndenumerate(cm):
    ax.text(j, i, f"{val}", ha='center', va='center')

ax.set_xticks([0,1])
ax.set_yticks([0,1])
ax.set_xticklabels(["Pred: Fail (0)", "Pred: Pass (1)"])
ax.set_yticklabels(["Actual: Fail (0)", "Actual: Pass (1)"])

plt.title("Confusion Matrix")
plt.show()

"""---
### **Debugging Keras**
In the real world, your neural networks will fail. Learning to read the error messages and identify poor training behavior is just as important as writing the code itself.
"""

new_model = Sequential()

new_model.add(Dense(16, activation='relu', input_shape=(5,)))
new_model.add(Dense(1, activation='sigmoid'))

new_model.compile(optimizer='adam', loss='binary_crossentropy')

new_model.fit(X_train_scaled, y_class_train, epochs=1, verbose=0)

"""### **What issues do you observe in this code?**

**Note**:

1. Keras will usually not throw any warnings or errors unless there is a catastrophic error that breaks the model.
2. Keras assumes that users can correctly specify the model and/or debug from plots
"""

new_model1 = Sequential()
new_model1.add(Input(shape=(3,)))
new_model1.add(Dense(16))
new_model1.add(Dense(8))
new_model1.add(Dense(1, activation='linear'))

new_model1.compile(optimizer='adam', loss='mse', metrics=['mae'])

print("Training model...")
new_model1_history = new_model1.fit(
    X_train_scaled,
    y_class_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=0 # Turn off printing
)
print("Training Completed")

new_model2 = Sequential()
new_model2.add(Input(shape=(3,)))
new_model2.add(Dense(16, activation='relu'))
new_model2.add(Dense(8, activation='relu'))
new_model2.add(Dense(1, activation='sigmoid'))

new_model2.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

print("Training model...")
new_model2_history = new_model2.fit(
    X_train_scaled,
    y_reg_train,
    epochs=20,
    batch_size=32,
    validation_split=0.2,
    verbose=0 # Turn off printing
)
print("Training Completed")

import matplotlib.pyplot as plt

# Set up a 2x2 grid for the plots (2 rows, 2 columns)
# Increased figsize height to 10 so the rows have room to breathe
fig, ((ax1, ax2), (ax3, ax4)) = plt.subplots(2, 2, figsize=(14, 10))

# --- Plot 1 (Top Left) ---
ax1.plot(new_model1_history.history['loss'], label='Training Loss', color='blue')
ax1.plot(new_model1_history.history['val_loss'], label='Validation Loss', color='orange')
ax1.axhline(y=0, color='red', linestyle='--', alpha=0.8) # Added zero line
ax1.set_title('Misspecified Classification Model \nnewmodel1')
ax1.set_xlabel('Epoch')
ax1.set_ylabel('Loss')
ax1.legend()
ax1.grid(True, linestyle='--', alpha=0.7)

# --- Plot 2 (Top Right) ---
ax2.plot(new_model2_history.history['loss'], label='Training Loss', color='blue')
ax2.plot(new_model2_history.history['val_loss'], label='Validation Loss', color='orange')
ax2.axhline(y=0, color='red', linestyle='--', alpha=0.8) # Added zero line
ax2.set_title('Misspecified Regression Model \nnewmodel2')
ax2.set_xlabel('Epoch')
ax2.set_ylabel('Loss (MSE)')
ax2.legend()
ax2.grid(True, linestyle='--', alpha=0.7)

# ==========================================
# BOTTOM ROW: THE CORRECT MODELS
# ==========================================

# --- Plot 3 (Bottom Left) ---
ax3.plot(class_history.history['loss'], label='Training Loss', color='blue')
ax3.plot(class_history.history['val_loss'], label='Validation Loss', color='orange')
ax3.axhline(y=0, color='red', linestyle='--', alpha=0.8) # Added zero line
ax3.set_title('Classification: Cross-Entropy Loss')
ax3.set_xlabel('Epoch')
ax3.set_ylabel('Loss')
ax3.legend()
ax3.grid(True, linestyle='--', alpha=0.7)

# --- Plot 4 (Bottom Right) ---
ax4.plot(reg_history.history['loss'], label='Training Loss', color='blue')
ax4.plot(reg_history.history['val_loss'], label='Validation Loss', color='orange')
ax4.axhline(y=0, color='red', linestyle='--', alpha=0.8) # Added zero line
ax4.set_title('Regression: Mean Squared Error (MSE)')
ax4.set_xlabel('Epoch')
ax4.set_ylabel('Loss (MSE)')
ax4.legend()
ax4.grid(True, linestyle='--', alpha=0.7)

# Adjust layout so titles and labels don't overlap
plt.tight_layout()
plt.show()

"""A common mistake is using the wrong output activation or loss function for
 your task. Below we train two intentionally broken models:

   new_model1: Regression architecture (linear output, MSE loss) trained on
               BINARY labels (0/1). MSE loss will technically run, but it is incorrect.
               
   new_model2: Classification architecture (sigmoid output, cross-entropy loss)
               trained on CONTINUOUS scores (0-100). Cross-entropy expects
               values between 0 and 1, so feeding it raw scores will produce
               unstable, nonsensical loss values.

---
# **Beyond Accuracy (Probabilistic Reliability)**
Right now, our classification model relies on a strict threshold: if the probability is > 0.50, we guess "Pass."

But a neural network doesn't actually output 1s and 0s; it outputs **probabilities**.
If our model says a student has a **90% chance of passing**, and we look at 100 students who got that exact same prediction, exactly 90 of them should have passed. If only 50 of them passed, our model is wildly overconfident.

To evaluate true measurement validity, we need to look at **Calibration Error**. Let's plot a Reliability Diagram to see if our model's confidence matches reality.

**How to read this chart:**
* **The Dotted Line:** This represents reality. If the model is perfectly reliable, its predictions will sit exactly on this line.
* **Below the Line (Overconfident):** If our blue line dips below the dotted line, the model is predicting high probabilities (e.g., 80%), but the true pass rate is much lower (e.g., 50%).
* **Above the Line (Underconfident):** If the blue line sits above the dotted line, the model is guessing low probabilities (e.g., 20%), but the actual pass rate is much higher (e.g., 40%).
"""

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

predicted_probs = class_model.predict(X_test_scaled, verbose=0).flatten()

# strategy='quantile' ensures every bin has an equal number of students
fraction_of_positives, mean_predicted_value = calibration_curve(
    y_class_test,
    predicted_probs,
    n_bins=10,
    strategy='quantile'
)

# 3. Plot the Reliability Diagram
plt.figure(figsize=(8, 6))
plt.plot([0, 1], [0, 1], "k:", label="Perfectly Calibrated", zorder=1)
plt.plot(mean_predicted_value, fraction_of_positives, "s-",
         label="Our Neural Network", color="blue", zorder=2)

plt.title('Reliability Diagram (Calibration Curve)')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('Actual Fraction of Passes')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.show()

"""# **Beyond Accuracy (Probabilistic Reliability)**

From the above plot we can see the model is reasonably well calibrated. There are other measurements we can do (e.g., Expected Calibration Error) which quantifies the amount of miscalibration we have.

Now let's plot the reliability diagram for the misspecified classification model
"""

from sklearn.calibration import calibration_curve
import matplotlib.pyplot as plt

predicted_probs = new_model1.predict(X_test_scaled, verbose=0).flatten()

# strategy='quantile' ensures every bin has an equal number of students
fraction_of_positives, mean_predicted_value = calibration_curve(
    y_class_test,
    predicted_probs,
    n_bins=10,
    strategy='quantile'
)

# 3. Plot the Reliability Diagram
plt.figure(figsize=(8, 6))
plt.plot([0, 1], [0, 1], "k:", label="Perfectly Calibrated", zorder=1)
plt.plot(mean_predicted_value, fraction_of_positives, "s-",
         label="Our Neural Network", color="blue", zorder=2)

plt.title('Reliability Diagram from Misspecified Model (Calibration Curve)')
plt.xlabel('Mean Predicted Probability')
plt.ylabel('Actual Fraction of Passes')
plt.legend()
plt.grid(True, linestyle='--', alpha=0.7)
plt.xlim(0, 1)
plt.ylim(0, 1)
plt.show()

"""### Part 4: SHAP Values
Neural networks are often criticized as "black boxes." If a student gets a 90% probability of passing, we need to be able to explain *why*.

To do this, we use **SHAP** (SHapley Additive exPlanations), the gold standard in explainable AI. SHAP uses game theory to calculate exactly how much each feature (Hours, Previous Score, Attendance) pushed a specific student's prediction up or down from the baseline average.

Let's generate a SHAP Summary Plot to see what the model actually learned about our students.
"""

# 1. Install the SHAP library (the -q keeps the output quiet)
print("Installing SHAP...")
!pip install shap -q
import shap

import warnings
warnings.filterwarnings('ignore') # Mutes warnings for now

print("Calculating SHAP values... (This can take a while)")

# 2. SHAP is VERY computationally heavy, so we give it a "background" sample
# of 100 training students to establish the baseline average
background = shap.sample(X_train_scaled, 100)

# 3. Create a wrapper function so SHAP can talk to our Keras model easily
predict_fn = lambda x: class_model.predict(x, verbose=0).flatten()

# 4. Build the Explainer
explainer = shap.KernelExplainer(predict_fn, background)

# 5. Calculate SHAP values for the first 50 students in our test set
# Why only 50? SHAP computes explanations by running thousands of permutations
# in the background for each individual...this can take days for large datasets
X_test_sample = X_test_scaled[:50]
shap_values = explainer.shap_values(X_test_sample)

# 6. Plot the results
feature_names = ['Hours_Studied', 'Previous_Score', 'Attendance_Rate']
shap.summary_plot(shap_values, X_test_sample, feature_names=feature_names)

"""**How to read the SHAP Summary Plot:**
* **Y-Axis (Features):** The features are ranked from most important (top) to least important (bottom).
* **X-Axis (SHAP Value):** Did this feature push the student's probability of passing higher (right of 0) or lower (left of 0)?
* **Color:** Red means the actual feature value was high (e.g., perfect attendance). Blue means the actual feature value was low (e.g., skipped a lot of class).

*Notice how high attendance (red dots) pushes the probability to the right, but low attendance (blue dots) drags it heavily to the left!*

**Can we use SHAP for variable selection?**
Short answer - I don't recommend it. Longer answer - It depends. SHAP is great for *understanding* the features, but it may not align with fair or valid predictions. This is very much a domain specific question.


Fryer, D., Strümke, I., & Nguyen, H. (2021). Shapley values for feature selection: The good, the bad, and the axioms. doi:10.48550/arXiv.2102.10936

Wang, H., Liang, Q., Hancock, J. T., & Khoshgoftaar, T. M. (2024). Feature selection strategies: a comparative analysis of SHAP-value and importance-based methods. Journal of Big Data, 11(1). doi:10.1186/s40537-024-00905-w
"""